// Auto-generated by scripts/generate-provider-registry.mjs. Do not edit manually.
import provider0 from "./aimlapi.js";
import provider1 from "./alicode-intl.js";
import provider2 from "./alicode.js";
import provider3 from "./alims-intl.js";
import provider4 from "./alitp-intl.js";
import provider5 from "./anthropic.js";
import provider6 from "./antigravity.js";
import provider7 from "./api-airforce.js";
import provider8 from "./assemblyai.js";
import provider9 from "./aws-polly.js";
import provider10 from "./azure.js";
import provider11 from "./baidu.js";
import provider12 from "./baseten.js";
import provider13 from "./bazaarlink.js";
import provider14 from "./black-forest-labs.js";
import provider15 from "./blackbox.js";
import provider16 from "./bluesminds.js";
import provider17 from "./brave-search.js";
import provider18 from "./byteplus.js";
import provider19 from "./cartesia.js";
import provider20 from "./cerebras.js";
import provider21 from "./chutes.js";
import provider22 from "./claude.js";
import provider23 from "./cline.js";
import provider24 from "./clinepass.js";
import provider25 from "./cloudflare-ai.js";
import provider26 from "./codebuddy-cn.js";
import provider27 from "./codebuddy-intl.js";
import provider28 from "./codex.js";
import provider29 from "./cohere.js";
import provider30 from "./comfyui.js";
import provider31 from "./commandcode.js";
import provider32 from "./coqui.js";
import provider33 from "./cursor.js";
import provider34 from "./deepgram.js";
import provider35 from "./deepinfra.js";
import provider36 from "./deepseek.js";
// import provider37 from "./devin-cli.js"; // hidden: spawns local agent with shell/fs access
import provider38 from "./edge-tts.js";
import provider39 from "./elevenlabs.js";
import provider40 from "./exa.js";
import provider41 from "./fal-ai.js";
import provider42 from "./featherless.js";
import provider43 from "./firecrawl.js";
import provider44 from "./fireworks.js";
import provider45 from "./fish-audio.js";
import provider46 from "./gemini-cli.js";
import provider47 from "./gemini.js";
import provider48 from "./github.js";
import provider49 from "./gitlab.js";
import provider50 from "./glm-cn.js";
import provider51 from "./glm.js";
import provider52 from "./google-pse.js";
import provider53 from "./google-tts.js";
import provider54 from "./grok-cli.js";
import provider55 from "./grok-web.js";
import provider56 from "./groq.js";
import provider57 from "./huggingface.js";
import provider58 from "./hyperbolic.js";
import provider59 from "./iflow.js";
import provider60 from "./inworld.js";
import provider61 from "./jina-ai.js";
import provider62 from "./jina-reader.js";
import provider63 from "./kilo-gateway.js";
import provider64 from "./kilocode.js";
import provider65 from "./kimchi.js";
import provider66 from "./kimi.js";
import provider67 from "./kiro.js";
import provider68 from "./linkup.js";
import provider69 from "./llm7.js";
import provider70 from "./local-device.js";
import provider71 from "./mimo-free.js";
import provider72 from "./minimax-cn.js";
import provider73 from "./minimax.js";
import provider74 from "./mistral.js";
import provider75 from "./mmf.js";
import provider76 from "./modal.js";
import provider77 from "./morph.js";
import provider78 from "./nanobanana.js";
import provider79 from "./nebius.js";
import provider80 from "./novita.js";
import provider81 from "./nvidia.js";
import provider82 from "./ollama-local.js";
import provider83 from "./ollama.js";
import provider84 from "./openai.js";
import provider85 from "./opencode-go.js";
import provider86 from "./opencode.js";
import provider87 from "./openrouter.js";
import provider88 from "./perplexity-agent.js";
import provider89 from "./perplexity-web.js";
import provider90 from "./perplexity.js";
import provider91 from "./playht.js";
import provider92 from "./poolside.js";
import provider93 from "./qoder.js";
import provider94 from "./recraft.js";
import provider95 from "./runwayml.js";
import provider96 from "./sambanova.js";
import provider97 from "./scaleway.js";
import provider98 from "./sdwebui.js";
import provider99 from "./searchapi.js";
import provider100 from "./searxng.js";
import provider101 from "./selfhosted-embedding.js";
import provider102 from "./selfhosted-stt.js";
import provider103 from "./selfhosted-tts.js";
import provider104 from "./serper.js";
import provider105 from "./siliconflow.js";
import provider106 from "./stability-ai.js";
import provider107 from "./tavily.js";
import provider108 from "./tencent.js";
import provider109 from "./together.js";
import provider110 from "./tokenrouter.js";
import provider111 from "./topaz.js";
import provider112 from "./tortoise.js";
// import provider113 from "./trae.js"; // hidden: no tool calling
import provider114 from "./venice.js";
import provider115 from "./vercel-ai-gateway.js";
import provider116 from "./vertex-partner.js";
import provider117 from "./vertex.js";
import provider118 from "./volcengine-ark.js";
import provider119 from "./voyage-ai.js";
// import provider120 from "./windsurf.js"; // hidden: no tool calling
import provider121 from "./xai.js";
import provider122 from "./xiaomi-mimo.js";
import provider123 from "./xiaomi-tokenplan.js";
import provider124 from "./youcom.js";
import provider125 from "./zed.js";

export default [
  provider0,
  provider1,
  provider2,
  provider3,
  provider4,
  provider5,
  provider6,
  provider7,
  provider8,
  provider9,
  provider10,
  provider11,
  provider12,
  provider13,
  provider14,
  provider15,
  provider16,
  provider17,
  provider18,
  provider19,
  provider20,
  provider21,
  provider22,
  provider23,
  provider24,
  provider25,
  provider26,
  provider27,
  provider28,
  provider29,
  provider30,
  provider31,
  provider32,
  provider33,
  provider34,
  provider35,
  provider36,
  // provider37, // devin-cli — hidden: spawns local agent with shell/fs access
  provider38,
  provider39,
  provider40,
  provider41,
  provider42,
  provider43,
  provider44,
  provider45,
  provider46,
  provider47,
  provider48,
  provider49,
  provider50,
  provider51,
  provider52,
  provider53,
  provider54,
  provider55,
  provider56,
  provider57,
  provider58,
  provider59,
  provider60,
  provider61,
  provider62,
  provider63,
  provider64,
  provider65,
  provider66,
  provider67,
  provider68,
  provider69,
  provider70,
  provider71,
  provider72,
  provider73,
  provider74,
  provider75,
  provider76,
  provider77,
  provider78,
  provider79,
  provider80,
  provider81,
  provider82,
  provider83,
  provider84,
  provider85,
  provider86,
  provider87,
  provider88,
  provider89,
  provider90,
  provider91,
  provider92,
  provider93,
  provider94,
  provider95,
  provider96,
  provider97,
  provider98,
  provider99,
  provider100,
  provider101,
  provider102,
  provider103,
  provider104,
  provider105,
  provider106,
  provider107,
  provider108,
  provider109,
  provider110,
  provider111,
  provider112,
  // provider113, // trae — hidden: no tool calling
  provider114,
  provider115,
  provider116,
  provider117,
  provider118,
  provider119,
  // provider120, // windsurf — hidden: no tool calling
  provider121,
  provider122,
  provider123,
  provider124,
  provider125,
];
